### ISSUE TITLE
smtpapi

### ISSUE THREAD

**Issue by paulocheque** [sendgrid/sendgrid-python#140]
Is this library a good strategy for Sendgrid? I believe sending an e-mail should be simple. If a developer need 3 days to implement this simple task, probably it will look for another company.

2 libraries does not make sense to me. It appears to be a useless complexity. The `smtpapi` library has just one class, what is the point of make this an independent library?

**Comment by thinkingserious** [comment]
We split the SMTPAPI library from the mail send library, because you can use them in two contexts: over SMTP only or within the mail send library.

So for those who only require the SMTPAPI library, they have a small focused library. And for those that need it within our mail send library, it's there as well.

Thanks for the feedback!
