### ISSUE TITLE
No errors raised (and no emails sent) with new account that failed provisioning

### ISSUE THREAD

**Issue by jackdesert** [sendgrid/sendgrid-python#143]
Please return an error when email fails to send due to account provisioning.

I created a new account, generated an API token, and sent an email using the following code (api token removed). It gives a 200 response, but no email is actually sent.

        import sendgrid

        API_KEY = "private"

        sg = sendgrid.SendGridClient(API_KEY, raise_errors=True)

        to = 'John Doe <example@gmail.com>'
        subject= 'Example'
        text = "Let's send some texta!"
        from_email = 'Support <support@example.com>'

        message = sendgrid.Mail(to=to, subject=subject, text=text, from_email=from_email)
        print (message)
        status, msg = sg.send(message)
        print (status)
        print (msg)

**Comment by iandouglas** [comment]
The problem is that SendGrid accepts the message because your account credentials match. It's only once the message is processed through their "mail pipeline" does the system realize your account is not yet provisioned and drops the message. This isn't something the Python library can support, it would be a bigger implementation detail for all SendGrid libraries to handle getting a notification back from the SMTP server or WebAPI that says "Yes, your credentials are good, but you're not provisioned"
