### ISSUE TITLE
Adding BCCs not intuitive

### ISSUE THREAD

**Issue by jasonab** [sendgrid/sendgrid-python#198]
#### Technical details:

* sendgrid-python Version: master (latest commit: [commit number])
* Python Version: 2.7

Apparently, the way to add a BCC is to call mail.personalizations[0].add_bcc(Email(bcc)) (according to the example), instead of calling mail.add_bcc(. I initially tried to add a new personalization, but that caused a 400 error (I assume because there was no to_address on the personalization, but there was no specific message about that).

So:
a. Personalizations are not well explained
b. Don't make adding a simple BCC so complicated
c. Don't assume that I know that there's a personalization on the email object, since I don't know that
d. Error reporting is very poor - if my personalization is malformed, tell me that directly when I try to send the email, instead of throwing a generic 400 error.

**Comment by thinkingserious** [comment]
@jasonab,

Thanks for the detailed feedback!

a. Agreed, we plan to migrate content from [here](https://sendgrid.com/docs/Classroom/Send/v3_Mail_Send/personalizations.html) and tailor specifically to how that translate to usage with this library

b. We will be updating the [Mail Helper](https://github.com/sendgrid/sendgrid-python/tree/master/sendgrid/helpers/mail) to make all the common use cases easier. Thanks for identifying this particular use case!

c. I will trying to figure out a better way of handling this through the Mail Helper. For now, I've added some comments to the README and examples that I hope will help in the mean time. If you have any other short term fix ideas, please let me know.

d. This is another area that will be getting attention. For now: https://github.com/sendgrid/sendgrid-python/blob/master/TROUBLESHOOTING.md#error

Feedback is very important to us as we believe the libraries should be community driven and SendGrid led. Since you took the time to detail out your feedback we'd like to send a small token of appreciation. Please email dx@sendgrid.com referring to this issue with your mailing address and T-Shirt size.

Thanks again!
