### ISSUE TITLE
Test issue - Hi Elmer!

### ISSUE THREAD

**Issue by mbernier** [sendgrid/sendgrid-python#278]
#### Issue Summary

A summary of the issue and the environment in which it occurs. If suitable, include the steps required to reproduce the bug. Please feel free to include screenshots, screencasts, code examples.

#### Steps to Reproduce

1. This is the first step
2. This is the second step
3. Further steps, etc.

Any other information you want to share that is relevant to the issue being reported. Especially, why do you consider this to be a bug? What do you expect to happen instead?

#### Technical details:

* sendgrid-python Version: master (latest commit: [commit number])
* Python Version: X.X

**Comment by tgwizard** [comment]
Hi @mbernier @thinkingserious! Hi really love the service SendGrid provides, and as an avid user of the sendgrid-python lib, I want to watch this repo to keep up to date. However, with all these bot test PRs, it is getting rather noisy. Would it be possible to test the bot on some other repo?

Cheers, and thanks for the good work!

**Comment by thinkingserious** [comment]
@tgwizard,


My apologies! I did not realize I was spamming all the watchers (facepalm).

I will stop immediately.

And thanks for the kind words :)

**Comment by thinkingserious** [comment]
Hello @mbernier,

Thanks for submitting a github issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team

**Comment by thinkingserious** [comment]
Please disregard, just testing.

**Comment by thinkingserious** [comment]
Hello @mbernier,

Thanks for submitting a github issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
