### ISSUE TITLE
Invalid params for example code

### ISSUE THREAD

**Issue by bakera81** [sendgrid/sendgrid-python#310]
#### Issue Summary

Some of the code examples supply parameters that cause the request to return 400 errors.

For example: https://github.com/sendgrid/sendgrid-python/blob/master/examples/contactdb/contactdb.py#L137

The docs for the v3 API do not include `list_id` as a query param, but in the above example it is included in the sample code: https://sendgrid.com/docs/API_Reference/Web_API_v3/Marketing_Campaigns/contactdb.html#List-Recipients-on-a-List-GET

#### Steps to Reproduce
```
# Copied from contactdb.py:
params = {'page': 1, 'page_size': 1, 'list_id': 1}
list_id = 1
response = sg.client.contactdb.lists._(list_id).recipients.get(query_params=params)
# >>> urllib.error.HTTPError: HTTP Error 400: BAD REQUEST
```
```
params = {'page': 1, 'page_size': 1}
list_id = 1
response = sg.client.contactdb.lists._(list_id).recipients.get(query_params=params)
# >>> All good
```

The examples were super helpful and were a great way to get started and it could make it even more efficient to get started with the API if they all matched the documentation.

#### Technical details:

* sendgrid-python Version: 4.0.0
* Python Version: 3.5

**Comment by thinkingserious** [comment]
Hello @bakera81,

Thanks for the heads up, I've added this to our backlog for a fix. 

With Best Regards,

Elmer

**Comment by waseem18** [comment]
Hi @thinkingserious 

I would like to take up this issue as a part of Hacktoberfest

:)

**Comment by xjlim** [comment]
Hi @thinkingserious, @waseem18 

I was looking into this as well and it seems like the [API](https://sendgrid.com/docs/API_Reference/Web_API_v3/Marketing_Campaigns/contactdb.html#List-Recipients-on-a-List-GET) is out of date.

The required query param `list_id` is removed from the v3 api for the endpoint `GET /contactdb/lists/{list_id}/recipients`.
```
{"errors":[{"message":"The following parameters are not custom fields or reservedfields: [list_id]"}]}
```

It seems like there are other tasks to be completed:
- [ ] update the [test](https://github.com/sendgrid/sendgrid-python/blob/master/test/test_sendgrid.py#L666)
- [ ] update the [docs](https://github.com/sendgrid/docs)
- [ ] update the [swagger](https://github.com/sendgrid/sendgrid-oai) 
in order to completely fix this.

**Comment by thinkingserious** [comment]
Hi @xjlim,

Thank you! There is also [one other place](https://sendgrid.com/docs/API_Reference/api_v3.html) to verify. 

With Best Regards,

Elmer

**Comment by waseem18** [comment]
Thanks @thinkingserious @xjlim for the information. I'll make the changes
