### ISSUE TITLE
SLA for Sendgrid "processed" event

### ISSUE THREAD

**Issue by dhruvg** [sendgrid/sendgrid-python#560]
#### Issue Summary

I notice that I don't reliably get `processed` events via the webhook. The odd thing is that I successfully receive `open` and `click` events for the same email which by definition occur after `processed`. For example, I just sent a batch of 100 emails and I got 17 `processed` events and 25 `open` events. I have no reason to believe that my server is overloaded. Am I just being impatient or is this a known issue? 

#### Technical details:

* sendgrid-python Version: 3.6.3
* Python Version: 3.5

**Comment by thinkingserious** [comment]
Hello @dhruvg,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
