### ISSUE TITLE
Why is the transaction email or any email going to SPAM folder? How can we resolve this issue?

### ISSUE THREAD

**Issue by jo-mongia** [sendgrid/sendgrid-python#574]
#### Issue Summary

I am using python integration code to send emails using sendgrid, but it is going to SPAM folder. From my observation I think the IP address is blacklisted. How can we resolve this issue and make the email delivered in INBOX.
What are the other possible reasons for emails getting delivered to SPAM folder?

#### Steps to Reproduce

1. This is the first step
2. This is the second step
3. Further steps, etc.

Any other information you want to share that is relevant to the issue being reported. Especially, why do you consider this to be a bug? What do you expect to happen instead?

#### Technical details:

* sendgrid-python Version: master (latest commit: [commit number])
* Python Version: X.X

**Comment by thinkingserious** [comment]
Hello @jo-mongia,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
