### ISSUE TITLE
Unicode Support???

### ISSUE THREAD

**Issue by lanshark** [sendgrid/sendgrid-python#575]
#### Issue Summary

SendGrid API, V3... The only mention of Unicode is in the API Overview, where it says it's NOT supported in personalizations from field.  That would IMPLY that it IS automatically supported everywhere else...

#### Steps to Reproduce

1. Create a message with unicode... attempt to send.. 
2. Fails

Maybe there is some magic I'm missing, but who knows... the doc's will never tell us!

#### Technical details:

* sendgrid-python Version: 5.3.0
* Python Version: 2.7.14

**Comment by thinkingserious** [comment]
Thanks for the heads up @lanshark. To be clear, where did you place the unicode? Subject, body, etc..? I will attempt to reproduce.

@ksigler7,

Do you have any insights regarding how this is documented? 

Thanks!

With Best Regards,

Elmer

**Comment by ksigler7** [comment]
I don't know! I'm digging into it though, this is a really good question

**Comment by thinkingserious** [comment]
Hello @lanshark,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
