### ISSUE TITLE
Update integration tests to utilize StopLight.io's Prism version v2.X

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/sendgrid-python#621]
#### Issue Summary

We use a mock server for integration/contract testing that is driven by our OpenAPI specification and StopLight.io's Prism service. The service is spun up utilizing the prism.sh script in this repo.

Before writing any code, we suggest you review our `CONTRIBUTING.md` file and propose your solution for discussion here in the comments. Thank you!

#### Aceptance Criteria

* we automatically use the latest v2.X version of Prism locally, in Travis CI and in Docker
* tests pass locally, in Travis CI and using Docker
* update `CONTRIBUTING.md` documentation, if necessary

#### Notes & References

* [Prism GitHub Repo](https://github.com/stoplightio/prism)

**Comment by meahow** [comment]
As far as I understand the topic, this is a matter of:

1. changing the install script (and dockerfiles) to get the latest 2.x prism instead of old 0.6.x
1. changing the way prism is started from `prism run` to `prism mock` or `prism validate`
1. updating `CONTRIBUTING.md`

If that's the case, then I will happily take this issue for Hacktoberfest 
I have tried the prism 2.x and after some minor fixes it ran the whole test suite fine.

The only issue is that it is about 50% slower then the 0.6 (at least on ma machine).

**Comment by meahow** [comment]
I'm on it!

**Comment by meahow** [comment]
I've just created PR #653 for this, but there are some issues with prism 2.x:
- 30% slower
- validate (prism2.x's new command for --no-mock) does not work properly with sendgrid
  - I got 502 bad gateway on a basic sendgrid example - `POST /v3/mail/send` (I don't know a way to debug it in sendgrid and wireshark shows only an encrypted stream)
  - it does work for basic GET and for petstore swagger example
- beforeScript seems to to stopped working
- with the current [OAI definition](https://github.com/sendgrid/sendgrid-oai/blob/91bb49a17071e2a9c6387d4d15b5a585d5e02e6b/oai_stoplight.json) validate passes requests to the same scheme as it gets them (http vs https) and because https is not functional on the mock server it requires a OAI change (swapping http with https in the scheme section

Adding this to the list of general prism downsides:
- can't do https on the mock side, at least not in this docker image (maybe it's just a matter of cinfiguration, but there's no documentation how to do this)
- closed source
- insufficient and outdated docs
- hard to troublleshoot/debug as there is no way to log the whole request coming in
  - in 0.6 the logged request was empty (no headers, no data)
  - in 2.0 the scripting is not working at all
- separate oai spec necessary for prism

I would recommend to look for some better mocking tool

**Comment by eshanholtz** [comment]
Closing this issue as the v4 branch is no longer being maintained.
