### ISSUE TITLE
Get back template html after processing for localhost development

### ISSUE THREAD

**Issue by phouri** [sendgrid/sendgrid-python#659]
#### Issue Summary

We are considering moving to templates for our development - so far we have been using django emails via sendgrid, and what we did when we are local we'd just print the html result of the email, allowing us to easily test stuff.

With template api - it's not possible to get back the html when doing sand - even when in sandbox mode, I'd expect sandbox results to return the post processed html for us to analyse and print.

#### Steps to Reproduce

Send a template api.

#### Technical details:

* sendgrid-python Version: 5.6.0 
* Python Version: 2.7

**Comment by thinkingserious** [comment]
Hello @phouri,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
