### ISSUE TITLE
After using sendgrid in django project, Resource not available error received 

### ISSUE THREAD

**Issue by Priyal-Trivedi** [sendgrid/sendgrid-python#748]
We have used Sendgrid for transactional emailers in our code base and following error is received since the time it has been merged on production server.

 Error: Err 11  Resource temporarily unavailable
<img width="606" alt="screenshot 2018-12-28 at 3 48 04 pm" src="https://user-images.githubusercontent.com/8300509/50512582-cf519000-0ab8-11e9-907d-8a35be5608dc.png">

The error mail were received on Sentry only after the email integration was done with Sendgrid.

* sendgrid-python Version: sendgrid==5.6.0
* Python Version: 2.7

**Comment by thinkingserious** [comment]
Hello @Priyal-Trivedi,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
