### ISSUE TITLE
Send grid is not Working on Python 3.6

### ISSUE THREAD

**Issue by JagadeeshBoyidi** [sendgrid/sendgrid-python#780]
#### Issue Summary

Hi Team,
I'm trying to send email using sendgrid it is working in python 3.7 but not working on python 3.6
could you please resolve the issue or provide any alternative solution to solve the problem

#### Technical details:

* sendgrid-python Version: master (latest commit: [commit number])
* Python Version: 3.6 and 3.7

**Comment by thinkingserious** [comment]
Hello @JagadeeshBoyidi,

Could you please provide some additional information so that we may try and reproduce ([since our 3.6 tests are passing](https://travis-ci.org/sendgrid/sendgrid-python/jobs/515965700))?

1. Can you share the source code you are trying to execute?
2. What is the error you receive?

Thank you!

With Best Regards,

Elmer

**Comment by JagadeeshBoyidi** [comment]
Please find source code below:

  content = 'Hi'
  sg = sendgrid.SendGridAPIClient(
      api_key = " api key here"
      )
  from_email = Email("abc***@gmail.com")
  to_email = Email("xyz***@gmail.com")
  subject = subject
  content = Content(
      "text/plain", content
      )
  mail = Mail(from_email, subject, to_email, content)
  response = sg.client.mail.send.post(request_body=mail.get())

Error I'm receiving:
TypeError: Object of type 'Email' is not JSON serializable

**Comment by JagadeeshBoyidi** [comment]
Hi ,
I've followed the instructions mentioned in the issue no #782  and now code is working fine .

Regards,
Jagadeesh
