### ISSUE TITLE
You are not authorized to access SendGrid, please contact Support.

### ISSUE THREAD

**Issue by 552277** [sendgrid/sendgrid-python#806]
#### Issue Summar
Hello, I'm sorry when I log in my account it occurs "You are not authorized to access SendGrid, please contact Support.", and my username and password are all right.
<img width="542" alt="Screen Shot 2019-05-22 at 16 00 59" src="https://user-images.githubusercontent.com/40648942/58157437-e03eb000-7caa-11e9-9008-aa9fb6e640ff.png">

#### Steps to Reproduce

My email is a ...@163.com email
After I sign up, it auto login successfully.
Then I log out and re-login, it will appear the case 

#### Technical details:

is it not support the 163 emails?

**Comment by thinkingserious** [comment]
Hello @552277,

I suggest that you reach out to our [support team](https://support.sendgrid.com) for further assistance. Thank you!

With Best Regards,

Elmer

**Comment by thinkingserious** [comment]
Hello @552277,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team

**Comment by Hafiz234** [comment]
I had the same problem. Would you please help me too? Thank you.

**Comment by lixach93** [comment]
I had the same problem. Would you please help me too? Thank you.

**Comment by blackinno** [comment]
I had the same problem. Would you please help me too? Thank you.

**Comment by skliarovartem** [comment]
I also have this problem. Your link to support team doesn't make sense because there a lot of menus and options. Disgusting...

**Comment by XIAOXIAOSIYU** [comment]
Got the same problem.

**Comment by Chriskuei** [comment]
Got the same problem.

**Comment by stokes776** [comment]
Got the same problem, was evaluating this for potential company use. Strange to see that my account can just be randomly turned off the day after I started trying to use it.

**Comment by Stephen195** [comment]
Got the same problem.

**Comment by likaiwen123** [comment]
The same problem, too.

**Comment by ammarhemani** [comment]
Got the same problem.

**Comment by szawruk** [comment]
Got the same problem

**Comment by adehuh** [comment]
I have same issue

**Comment by strideynet** [comment]
Same issue wtf

**Comment by pankaj-bt** [comment]
Any solution ? Not able to login.

**Comment by likaiwen123** [comment]
I have submitted an issue on this login problem after encountering this problem at SendGrid's Website rather than GitHub, and the sendgrid team has sent me an email and helped me out, maybe you guys can also try that. The website url is `https://support.sendgrid.com/hc/en-us/requests/new#login-issue`

**Comment by sebsronnie** [comment]
Same problem - 2 days after I started using SendGrid.

**Comment by bahaa-ka** [comment]
Same here
and the support is not available.

**Comment by rootraid** [comment]
I have the same problem!!
After the hustle to register (which they made me write to customer support to activate) I spent the day reading their poorly written documentation. I had finally started the test setup, when I tried login in and found myself blocked (You are not authorized to access SendGrid, please contact Support.).

I've tried emailing "support" but since I am not able to login I doubt my emails will get the priority I need...

I only had the weekend to work on this, and my time is now wasted... thanks sendgrid!!

Not a company I would recommend to anyone so far.........

**Comment by SafaaKHADIM** [comment]
same problem

**Comment by childish-sambino** [comment]
This is not something that can be fixed in this library and is an issue that only support can resolve. Please submit a request for login support here: https://support.sendgrid.com/hc/en-us/requests/new#login-issue

**Comment by nu11secur1ty** [comment]
And now in 2020, the problem is the same. So Did you decide to fix this stupid request or not?

**Comment by abeerwaseem** [comment]
Same issue, first my emails are not processing then this issue, its disgusting and such a waste of time.

**Comment by fordiy** [comment]
I canot login I got message: You are not authorized to access SendGrid, please contact Support. 
Hey, Sendgrid, PLEASE leave a form for user cannot loggin to contact you! It's rude if user paid you, and you cannot allow to login. Do you still monthly charge our credit card?!

**Comment by childish-sambino** [comment]
@fordiy Are you able to use this form for help logging in? https://support.sendgrid.com/hc/en-us/requests/new#login-issue

**Comment by NikhilP97** [comment]
Got the same problem

**Comment by childish-sambino** [comment]
@NikhilP97 Let's track it here: https://github.com/sendgrid/sendgrid-python/issues/874

**Comment by childish-sambino** [comment]
@abeerwaseem Are you able to use this form for help logging in? https://support.sendgrid.com/hc/en-us/requests/new#login-issue

**Comment by AlbertAndMayIT** [comment]
Same issue here... Wanted to try them out but they are obviously unreliable.

**Comment by childish-sambino** [comment]
@AlbertAndMayIT Are you able to use this form for help logging in? https://support.sendgrid.com/hc/en-us/requests/new#login-issue

**Comment by AlbertAndMayIT** [comment]
What is going on? Please fix your platform. I dont know why this
is happening.
