### ISSUE TITLE
In-Reply-To and References headers not being picked up to show conversation history

### ISSUE THREAD

**Issue by ssp573** [sendgrid/sendgrid-python#825]
#### Issue Summary

I am trying to send a reply to an email by adding the in-reply-to and references headers using the python library. I expect it to generate an email in the recipients inbox which has all previous messages in the conversation as well. I have added the following headers to test with an email thread with one previous message:

`
mail.personalizations[0].add_header(Header("In-Reply-To", data['In-Reply-To']))
mail.personalizations[0].add_header(Header("References", data['In-Reply-To']))
`

data['In-Reply-To'] is the message id of the email that I want to reply to. I have also tried changing the subject of the email to include the previous email's subject. The headers are added in the email but the previous conversation does not show up. Any way I could get this working?

#### Technical details:

* sendgrid-python Version: 6.0.5
* Python Version: 3.6.8

**Comment by thinkingserious** [comment]
Hello @ssp573,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
