### ISSUE TITLE
Using HTML FileUpload to add attachment error

### ISSUE THREAD

**Issue by connelevalsam** [sendgrid/sendgrid-python#830]
#### Issue Summary

I'm trying to upload a file using HTML FileUpload input field and send it as attachment, but I get an error.
`Object of type InMemoryUploadedFile is not JSON serializable`
It sends if I don't add a file. Here's my code

`
if request.method == 'POST':
        msg.status = "Accepted"
        reply = request.POST.get("reply")
        
        message = Mail(
            from_email=("info@me.com", "Me"),
            to_emails=mail,
            subject='Request Accepted',
            html_content=reply
        )
        if request.FILES:
            f = request.FILES.get("fileToUpload", False)
            """Build attachment"""
            attachment = Attachment()
            attachment.file_content = FileContent(f)
            attachment.file_type = FileType("application/pdf")
            attachment.file_name = FileName("me_invoice.pdf")
            attachment.disposition = Disposition("attachment")
            attachment.content_id = ContentId("Invoice PDF ID")
            message.attachment = attachment
        try:
            response = sg.send(message)
            print("Mail sent")
            print("===========Status code======\n", response.status_code)
            print("===========body=============\n", response.body)
            print("=============headers========\n", response.headers)
            msg.save()
        except Exception as e:
            print(e)
            return redirect('message-accept', pk = msg.id)
`

* sendgrid-python Version: sendgrid==6.0.5
* Python Version: 3.6

**Comment by thinkingserious** [comment]
Hello @connelevalsam,

The value of `f` in your example should be [base64](https://docs.python.org/2/library/base64.html) encoded. Can you try that and let me know how it goes?

If that does not work, could you please post the [request body](https://github.com/sendgrid/sendgrid-python/blob/master/TROUBLESHOOTING.md#viewing-the-request-body) so that I may try and reproduce (please do not include any sensitive data).

Thank you!

With best regards,

Elmer
