### ISSUE TITLE
Problems sending emails at specific time

### ISSUE THREAD

**Issue by sknzl** [sendgrid/sendgrid-python#833]
Recently I added a new task to Celery to send an email at 6.00 UTC every day. However the response is:
```
HTTPError 401: 'Unauthorized'
```
Usually this would indicate a wrong API key or something similar, but I use the same function to send any other email and it works. When I change the Celery task to a time after 6.00 UTC, for example today I tried with 6.45 UTC, everything worked as expected. All emails were sent and I didn't receive the error HTTPError 401: 'Unauthorized', and nothing but the time was changed.

For testing, to exclude any problem with environment variables, the API key was hard-coded
```
sg = sendgrid.SendGridAPIClient(apikey='SG.XXXX')
```

The email is sent with

```
response = sg.client.mail.send.post(request_body=mail.get())
```

I'm not really sure, what is going on. Is it possible that your API refuses connections at exactly 6.00 UTC?

I know it's a long shot, but I don't have any other explanation until now.

#### Technical details:

* sendgrid-python Version: 5.6.0
* Python Version: 3.6.8

**Comment by thinkingserious** [comment]
Hello @sknzl,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
