### ISSUE TITLE
Google Analytics and UTM tags

### ISSUE THREAD

**Issue by HUSSTECH** [sendgrid/sendgrid-python#834]
#### Issue Summary

When Google Analytics is enabled on messages sent via the v3 api, and the utm tags are either not set or set to `None` or an empty string, links will have a default set of utm tags on them.

I only would like to set one utm tag `utm_medium`, however it looks like a full set of all the other utm tags are added onto the link. This must be somewhere in the sendgrid backend/pipes because I can't see anywhere in the code where utm tags are set to a default value if they are left `None`/blank. Is this expected behaviour?

#### Steps to Reproduce

1. use the example code below to send an email with Google Analytics enabled (this is for v5.3.0, but you'll get the same result with all versions.)
```
        tracking_settings = TrackingSettings()
        tracking_settings.ganalytics = Ganalytics(enable=True, utm_medium="email", utm_source="", utm_term="", utm_content="",  utm_campaign="")
        mail.tracking_settings = tracking_settings
```
2. click a link in the send email, and you will see the utm parameters are all set, even though just utm_medium was set.
```
/?utm_medium=email&utm_campaign=website&utm_source=sendgrid.com
```

The section of the docs dealing with this is [here](https://sendgrid.com/docs/ui/account-and-settings/tracking/), however the link on the page pointing to ["Google Analytics"](https://sendgrid.com/ui/analytics-and-reporting/google-analytics/) is currently broken.

#### Technical details:

* sendgrid-python Version: 5.3.0
* Python Version: 3.6

**Comment by eshanholtz** [comment]
Hi @HUSSTECH,

I personally haven't been able to reproduce this error with the v5.3.0 sendgrid python library, yet, but one thing I want to point out, though, is that by initializing the Ganalytics object with `utm_{blah}=""`, you're forcing those fields to have a value of empty string, instead of letting the library default initialize those fields to `None`. This initializer for the `Ganalysics` object, including default parameters, can be found [here](https://github.com/sendgrid/sendgrid-python/blob/021a9dc7dd2a9be955e50c53bd5fa4c313b11c15/sendgrid/helpers/mail/ganalytics.py#L4).

What happens to the `utm` parameters when you use the following code to set the tracking settings?

```python
tracking_settings = TrackingSettings()
tracking_settings.ganalytics = Ganalytics(enable=True, utm_medium="email")
mail.tracking_settings = tracking_settings
```

Also, the link to the Google Analytics docs from the [tracking settings docs](https://sendgrid.com/docs/ui/account-and-settings/tracking/) has been fixed, as far as I can tell!

**Comment by HUSSTECH** [comment]
Hello @eshanholtz 

Thanks for looking into this issue! I just tried the code snippet exactly as shown in your reply, but I still am getting the other utm fields being set. This is what I got `?utm_source=sendgrid.com&utm_medium=email&utm_campaign=website`.

I'm going to open an internal ticket so I can supply the message sg id, and maybe that could help with tracing my message/api request through the system. 

All the links seem fixed now on the docs, thanks to whoever did that!

**Comment by HUSSTECH** [comment]
Sendgrid support ref Request #2617427

**Comment by thinkingserious** [comment]
Hello @HUSSTECH,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
