### ISSUE TITLE
Not receiving emails in GSUITE sent to my own domain

### ISSUE THREAD

**Issue by d6tdev** [sendgrid/sendgrid-python#891]
I'm not seeing those emails come through. It works if I send outside my domain including my private gmail. But not when sent to my an email on my own domain which is managed with GSUITE.

```python
    sg = sendgrid.SendGridAPIClient(os.environ.get('SENDGRID_API_KEY'))
    from_email = "Support <support@mydomain.com>"
    subject = "Log: hello world"
    content = "hello world"
    to_email = ['me@gmail.com'] # email arrives
    to_email = ['me@mydomain.com'] # email NOT arrives

    message = Mail(from_email=from_email, to_emails=to_email, subject=subject, plain_text_content=content)
    response = sg.send(message)
    print(response.status_code)
    print(response.body)
    print(response.headers)
```

202
b''
Server: nginx
Date: Thu, 07 May 2020 02:30:09 GMT
Content-Length: 0
Connection: close
Access-Control-Allow-Origin: https://sendgrid.api-docs.io
Access-Control-Allow-Methods: POST
Access-Control-Allow-Headers: Authorization, Content-Type, On-behalf-of, x-sg-elas-acl
Access-Control-Max-Age: 600
X-No-CORS-Reason: https://sendgrid.com/docs/Classroom/Basics/API/cors.html

### Technical details:
* sendgrid-python version: sendgrid==6.3.0
* python version: Python 3.7.4 (default, Aug  9 2019, 18:34:13) [MSC v.1915 64 bit (AMD64)] :: Anaconda, Inc. on win32

**Comment by thinkingserious** [comment]
Hello @d6tdev,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
