### ISSUE TITLE
Got the same problem.

### ISSUE THREAD

**Issue by rolos37** [sendgrid/sendgrid-python#900]
Got the same problem.
It won't let me sing in, nor contact support even with a paying account.

_Originally posted by @Stephen195 in https://github.com/sendgrid/sendgrid-python/issues/806#issuecomment-557139884_

**Comment by thinkingserious** [comment]
Hello @rolos37,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
