### ISSUE TITLE
Unauthorized Error

### ISSUE THREAD

**Issue by Souldiv** [sendgrid/sendgrid-python#905]
### Issue Summary
I recently bought the essentials plan service but after crossing 100 mails it says that I have gone over the quota I have created a support request on sendgrid website but have gotten no response as of now. I have checked my API keys, they all lead to UnauthorizedError when I tried to send a mail.  I have also checked what my email API plan is set to, on the portal it shows that I am using the essentials plan service and not the free one.

here is the support ticket:
support.sendgrid.com/hc/requests/4530683

### Exception/Log
![sendgrid](https://user-images.githubusercontent.com/25404248/84470454-044ba580-aca1-11ea-9fb4-4eb80b00eebe.JPG)

### Technical details:
* sendgrid-python version: 5.4.1
* python version: 3.7.4

**Comment by thinkingserious** [comment]
Hello @Souldiv,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team

**Comment by childish-sambino** [comment]
I've bumped the support team to take a look.

**Comment by Souldiv** [comment]
My account was not bumped to the plan I had bought. It is done now, thanks anyways.
