### ISSUE TITLE
You are not authorized to access SendGrid

### ISSUE THREAD

**Issue by towhaEL** [sendgrid/sendgrid-python#919]
Hello I am facing login issues. Still not solved . I need support.
I sign up my account using github student pack. After sign up it automatically logged me out. Now when I try to sign in my account it says you are not authorized to access Sendgrid. I have also submitted a ticket 1 week before in support.sendgrid.com  , but don't receive any support from you yet. I also mail to Sendgrid support team. Still no response.
my email : towhae@gmail.com

![Screenshot_2020-07-04-00-04-29-315_com android chrome](https://user-images.githubusercontent.com/37008991/86491305-3f1a9800-bd8c-11ea-9660-1fa8c6867b50.jpg)

**Comment by LZL0** [comment]
Same here. They do it to all of their `valued` customers.

**Comment by z-t-y** [comment]
Same here. Was it solved?

**Comment by thinkingserious** [comment]
Hello @towhaEL,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team

**Comment by childish-sambino** [comment]
https://github.com/sendgrid/sendgrid-python/blob/master/TROUBLESHOOTING.md

> If you have an issue logging into your Twilio SendGrid account, please read this [document](https://sendgrid.com/docs/ui/account-and-settings/troubleshooting-login/). For any questions regarding login issues, please contact our [support team](https://support.sendgrid.com).
