### ISSUE TITLE
You are not authorized to access SendGrid, please contact Support.

### ISSUE THREAD

**Issue by ErxrilOwl** [sendgrid/sendgrid-python#930]
Same issue to other people. Tried contacting the support but it's almost 2 weeks now and no response.

**Comment by thinkingserious** [comment]
Hello @ErxrilOwl,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team

**Comment by childish-sambino** [comment]
It sounds like your account status might be under review. You should have received [a notice](https://sendgrid.com/docs/ui/account-and-settings/account-under-review/) in your e-mail with more details.

If you would like to discuss it, please respond to the email you received regarding the notice. 

If you cannot find this e-mail, we ask our customers do the following:

> 
> 1. Go to [support.sendgrid.com](https://support.sendgrid.com/hc/en-us)
> 2. Click on Trouble Logging In
> 3. Click "I am having a different log in issue"
> 
> To reactivate your account, you may be prompted to outline your sending practices for support to vet and either reactivate or keep closed. Unfortunately, there is not a way around this since this vetting process is put in place by Compliance to prevent bad actors from misusing our product.

Support cannot assist in reactivation of banned accounts.

Hope this helps!
Twilio SendGrid Team
