### ISSUE TITLE
You are not authorized to access sendgrid.

### ISSUE THREAD

**Issue by ats1999** [sendgrid/sendgrid-python#959]
https://github.com/sendgrid/sendgrid-python/issues/806

I have the same problem as the issue above. In my case, i have my email account like abc@gmail.com .

I tried contacted sendgrid many times, but i didn't get any response.

**Comment by thinkingserious** [comment]
Hello @ats1999,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team

**Comment by JenniferMah** [comment]
@ats1999 
This is not something that can be fixed in this library and is an issue that only support can resolve. Have you already submitted a request in this form? https://support.sendgrid.com/hc/en-us/requests/new#login-issue Please post or email me your SendGrid username and the email you used for the form above so that I can follow up.

**Comment by ats1999** [comment]
I have contacted them many times, but i didn't get any reply.

**Comment by ats1999** [comment]
> email me your SendGrid username
I don't have you email id,
Should i write my email here.

**Comment by JenniferMah** [comment]
@ats1999 
Yes please reply with a comment that includes your email and SendGrid username.
