### ISSUE TITLE
python_http_client.exceptions.ForbiddenError: HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by ClimenteA** [sendgrid/sendgrid-python#978]
I'm not sure why I get a `ForbiddenError` when I try to send an email.

Here is what I use to test:
```py
import sendgrid
import os, logging
from sendgrid.helpers.mail import Mail

from dotenv import load_dotenv
load_dotenv()

logging.warning('SENDGRID_API_KEY ' + str(os.getenv('SENDGRID_API_KEY')))  # I see the API KEY (the long secret key)

mail_client = sendgrid.SendGridAPIClient(api_key=os.getenv('SENDGRID_API_KEY'))
mail = Mail(
    from_email='Single Sender Verification Email which is verified', 
    subject='test', 
    to_emails=['another email]', 
    html_content='test content'
)

response = mail_client.send(mail)

```
Here is the error I got:
```
...python_http_client/client.py", line 184, in _make_request
    raise exc
python_http_client.exceptions.ForbiddenError: HTTP Error 403: Forbidden
```

My IP appears in `IP access management` section not sure if it's connected to me trying to send emails.

- `sendgrid==6.6.0`
- `Python 3.8.5`
- `ubuntu 20.04`

**Comment by thinkingserious** [comment]
Hello @ClimenteA,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
